service: lambda-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-offline

functions:
  timeslots:
    handler: dist/timeslots/handler.getTimeslots
    events:
      - http:
          path: /timeslots
          method: get
