service: lambda-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    platform: "node"
    mainFields:
      - main
    packager: yarn
    bundle: true
    minify: false
    sourcemap: false
    keepNames: true
    plugins: ./esbuild.plugins.cjs

  offline:
    useChildProcesses: true

functions:
  timeslots:
    handler: src/timeslots/handler.getTimeslots
    events:
      - http:
          path: /timeslots
          method: get
  timeslotsById:
    handler: src/timeslots/handler.getTimeslotById
    events:
      - http:
          path: /timeslots/{id}
          method: get
