service: lambda-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    sourcemap: false
    keepNames: true
  offline:
    useChildProcesses: true

functions:
  timeslots:
    handler: src/timeslots/handler.getTimeslots
    events:
      - http:
          path: /timeslots
          method: get
